# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    container_name: details-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: details-db
      POSTGRES_USER: details-db
      POSTGRES_PASSWORD: details-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
